---
eda_decision_environments:
  - name: AIOps-Decision-Environment
    description: Decision environment for AIOps intelligent remediation rulebooks
    image_url: quay.io/ansible/ansible-rulebook:latest
