---
controller_credentials:
  - name: "CyberArk-Cred"
    description: ""
    credential_type: "CyberArk Central Credential Provider Lookup"
    organization: "AwesomeCorp"
    inputs:
      app_id: ''
      url: https://cyberark.example.com
      verify: false
      webservice_id: ''

...
