---
controller_credentials:
  - name: "DevOps-From-CyberArk"
    description: ""
    credential_type: "Machine"
    organization: "AwesomeCorp"
    inputs:
      become_method: ''
      become_username: ''
      username: devopsadmin

...
