---
controller_validate_certs: false
controller_username: "{{ vault_controller_username | default(lookup('env', 'CONTROLLER_USERNAME')) }}"
controller_password: "{{ vault_controller_password | default(lookup('env', 'CONTROLLER_PASSWORD')) }}"
controller_hostname: "{{ vault_controller_hostname | default(lookup('env', 'CONTROLLER_HOST')) }}"

aap_username: admin
aap_password: aapadmin
aap_hostname: https://aap25.lab.iamgini.com
aap_validate_certs: false

export_dir: controller_config_export

aap_configs_dir: ../cac_sample
controller_dependency_check: false
