---
controller_settings:
  - settings:
      TOWER_URL_BASE: "https://13.55.176.159"
      LICENSE:
        account_number: '5910538'
        instance_count: 100
        license_date: '1798779599'
        license_type: enterprise
        pool_id: 8a85f99c7d76f2fd017d96c9f1e606bb
        product_name: Red Hat Ansible Automation Platform, Standard (100 Managed Nodes)
        satellite: false
        sku: MCT3691
        subscription_id: '10433839'
        subscription_name: Red Hat Ansible Automation Platform, Standard (100 Managed Nodes)
        support_level: Standard
        trial: false
        usage: ''
        valid_key: true
      INSTALL_UUID: "09f33236-5243-48b1-803c-2e175b87b3e5"
      INSIGHTS_TRACKING_STATE: "false"
      CLEANUP_HOST_METRICS_LAST_TS: "2026-04-29T08:21:56.263100Z"
      HOST_METRIC_SUMMARY_TASK_LAST_TS: "2026-04-29T08:51:58.286124Z"
      PENDO_TRACKING_STATE: "off"
...
