---
- name: Resources under organization
  when: resource_content.organization.name is defined
  block:
    - name: Ensure directory exists - {{ resource_item }}
      ansible.builtin.file:
        path: "{{ export_controller_target_dir }}/organizations/{{ resource_content.organization.name }}/{{ resource_item }}"
        state: directory
        mode: "0755"

    - name: Save the content inside the directory
      ansible.builtin.copy:
        content: "{{ resource_content | to_nice_yaml }}"
        dest: "{{ export_controller_target_dir }}/organizations/{{ resource_content.organization.name }}/{{ resource_item }}/{{ resource_content.name | regex_replace('/',
          '_') }}.yaml"
        mode: "0755"
      when: resource_item != 'users'

    - name: Save the content inside the directory
      ansible.builtin.copy:
        content: "{{ resource_content | to_nice_yaml }}"
        dest: "{{ export_controller_target_dir }}/organizations/{{ resource_content.organization.name }}/{{ resource_item }}/{{ resource_content.username | regex_replace('/',
          '_') }}.yaml"
        mode: "0755"
      when: resource_item == 'users'

- name: Resources under NO organization
  when: not resource_content.organization.name is defined
  block:
    - name: Ensure directory exists for NULLORGANIZATION
      ansible.builtin.file:
        path: "{{ export_controller_target_dir }}/organizations/NULLORGANIZATION/{{ resource_item }}"
        state: directory
        mode: "0755"

    - name: Save the content inside the directory
      ansible.builtin.copy:
        content: "{{ resource_content | to_nice_yaml }}"
        dest: "{{ export_controller_target_dir }}/organizations/NULLORGANIZATION/{{ resource_item }}/{{ resource_content.name | regex_replace('/', '_') }}.yaml"
        mode: "0755"
      when: resource_item != 'users'

    - name: Save the content inside the directory
      ansible.builtin.copy:
        content: "{{ resource_content | to_nice_yaml }}"
        dest: "{{ export_controller_target_dir }}/organizations/NULLORGANIZATION/{{ resource_item }}/{{ resource_content.username | regex_replace('/', '_') }}.yaml"
        mode: "0755"
      when: resource_item == 'users'
