---
controller_instance_groups:
  - name: "controlplane"
    policy_instance_minimum: "0"
    policy_instance_percentage: "100"
    instances:
      - "13.55.176.159"
  - name: "default"
    policy_instance_minimum: "0"
    policy_instance_percentage: "100"
    instances:
      - "13.55.176.159"
...
