---
controller_inventory_sources:
  - name: "from-git"
    description: ""
    organization: "AwesomeCorp"
    source: "scm"
    source_project: "Infra Automation"
    source_path: "demohosts.ini"
    inventory: "Cac-Test"
    update_on_launch: "False"
    overwrite: "False"
