---
controller_credentials:
  - name: "Cac_DevOps"
    description: ""
    credential_type: "Machine"
    organization: "ORGANIZATIONLESS"
    inputs:
      become_method: ''
      become_username: ''
      password: ''
      username: devops

...
