---
- name: Ansible Controller Export
  hosts: localhost
  connection: local
  gather_facts: false
  # collections:
  #   # - awx.awx
  #   - ansible.controller
  # environment:
  #   CONTROLLER_HOST: http://192.168.49.2:30080
  #   CONTROLLER_USERNAME: admin
  #   CONTROLLER_PASSWORD: replace-me
  #   CONTROLLER_VERIFY_SSL: False

  # vars:
  #   controller_validate_certs: false
  #   controller_username: "{{ vault_controller_username | default(lookup('env', 'CONTROLLER_USERNAME')) }}"
  #   controller_password: "{{ vault_controller_password | default(lookup('env', 'CONTROLLER_PASSWORD')) }}"
  #   controller_hostname: "{{ vault_controller_hostname | default(lookup('env', 'CONTROLLER_HOST')) }}"

  # export_items:
#   - credentials
  vars:
    export_controller_target_dir: "{{ playbook_dir }}/cac_exported"
    export_organizations:
      - 'AwesomeCorp'
      # - 'ACME'
    export_credentials: all
    export_credential_types: all
    export_inventories: all
    export_projects: all
    export_job_templates: all

  tasks:
    - name: Export the configurations
      ansible.builtin.include_role:
        name: controller_export
